// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo9XuoHH-JfSdMkAgNv8e2uR-r4mo4SQA',
    appId: '1:803876004366:web:ba9bb93d2af7fb5d36d25f',
    messagingSenderId: '803876004366',
    projectId: 'weather-app-24112023',
    authDomain: 'weather-app-24112023.firebaseapp.com',
    storageBucket: 'weather-app-24112023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAsmf5Q83wMXzTSD1R46UjdMtGhH5nQY',
    appId: '1:803876004366:android:2ee1b3ca5ec1c62c36d25f',
    messagingSenderId: '803876004366',
    projectId: 'weather-app-24112023',
    storageBucket: 'weather-app-24112023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALPWqUgurh_MizwaOywFYKraFrkYyaHRQ',
    appId: '1:803876004366:ios:b6770d1da8acf15336d25f',
    messagingSenderId: '803876004366',
    projectId: 'weather-app-24112023',
    storageBucket: 'weather-app-24112023.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
